### ISSUE TITLE
E2E tests with protractor 

### ISSUE THREAD

**Issue by mortterna** [CSC-IT-Center-for-Science/iow-ui#445]
# Sections
- [x] Frontpage
- [x] Add model
- [x] Edit model
- [x] Model vocabularies
- [x] Model reference data
- [x] Model links
- [x] Model namespaces
- [x] Remove model
- [x] Add class (by concept, reference, external)
- [x] Add predicate (by concept, reference, external)
- [x] Edit class
- [x] Add property (by concept, existing predicate, external)
- [x] Edit property
- [x] Property predicate view
- [x] Edit predicate
- [x] Remove class
- [x] Remove predicate
- [x] Remove property
- [ ] Concept editor ! wont fix before termeditor is in use
